// Generated by QingheSimulation.export_contracts from answer_protocol.py.
export const answerProtocolVersion = "qinghe-answer-protocol/1" as const;
export type AnswerResponseKind = "abstain" | "answer" | "continue" | "help" | "partial" | "question";
export type StudentAttempt = { "selected_option_ids": Array<string> } | { "value": boolean } | { "values": Record<string, string> } | { "content": string } | { "result": string; "unit"?: string | null; "steps"?: Array<string> } | { "result"?: string | null; "unit"?: string | null; "steps": Array<string> };
export type AnswerTarget = { "item_id": string | null; "part_id": string | null };
export interface AnswerResponse {
  "text": string;
  "response_kind": AnswerResponseKind;
  "attempt": StudentAttempt | null;
  "target": AnswerTarget;
  "answer"?: string | boolean | null | Array<string> | Record<string, string>;
  "answer_protocol_version"?: "qinghe-answer-protocol/1";
  "answer_audit"?: string;
  "intent"?: "continue" | "resolved" | "next_question" | "leave";
}
