'use client';
import { useEffect,useRef,useState,useCallback } from 'react';
import { Building2,School,TreePine,MousePointer2,Home,Landmark,Layers3,Compass,Plus,Minus,Maximize,Pause,Play,Sun,Moon,Users,Move,MapPin,Clock3,ChevronRight,X,HelpCircle,Trash2,Navigation,Check } from 'lucide-react';
import { Tooltip,TooltipContent,TooltipProvider,TooltipTrigger } from '@/components/ui/tooltip';
import { Switch } from '@/components/ui/switch';
import { Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription } from '@/components/ui/sheet';
import { W,H,TYPE_NAMES,createWorld,updateAgents,place,riverX,type World,type Tool,type Building } from '@/lib/world/model';
import { registerCityTools } from '@/lib/world/agent-tools';
import { renderGround,renderObjects,drawAgents,drawNight,drawBuilding,drawTree } from '@/lib/world/render';
type Camera={x:number;y:number;zoom:number};
type Engine={world:World;camera:Camera;refresh:()=>void;focus:(b?:Building)=>void;zoom:(v:number)=>void;edit:(tool:Tool,x:number,y:number)=>string};
const places=[{name:'青禾小学',sub:'启蒙与成长',color:'#efb961',icon:School},{name:'明德初中',sub:'探索更大的世界',color:'#80b9d2',icon:School},{name:'青河一中',sub:'青春与理想',color:'#e29179',icon:School},{name:'青河大学',sub:'知识与创新',color:'#b3a2d3',icon:Landmark}];
const descriptions:Record<string,string>={home:'街角的小院、沿路的花圃，还有窗后亮着的灯。这里是青河居民生活的地方。',primary:'有彩色教学楼、小型球场和活动庭院的社区小学。',middle:'教学楼与绿茵操场相伴，连接住宅社区与城市主街。',high:'红色跑道围绕着运动场，校门外就是宽阔的青河大道。',university:'东岸的开放校园，拥有教学楼、图书馆、中心喷泉与运动场。',hall:'青河市的公共地标，门前的喷泉广场是居民会面的地方。',tower:'矗立在东岸步道旁的钟楼，从桥上也能看见它的尖顶。',library:'河畔的公共阅读空间，树荫与安静的庭院围绕着它。',shop:'面向街道的小店，让城市的日常生活更丰富。'};
function IconButton({label,children,onClick,active=false}:{label:string;children:React.ReactNode;onClick:()=>void;active?:boolean}){return <Tooltip><TooltipTrigger render={<button className={`icon-button ${active?'active':''}`} aria-label={label} onClick={onClick}/>}>{children}</TooltipTrigger><TooltipContent>{label}</TooltipContent></Tooltip>}
export default function City(){
  const canvasRef=useRef<HTMLCanvasElement>(null),miniRef=useRef<HTMLCanvasElement>(null),engine=useRef<Engine|null>(null);
  const [tool,setTool]=useState<Tool>('explore'),[paused,setPaused]=useState(false),[speed,setSpeed]=useState(1),[labels,setLabels]=useState(true),[grid,setGrid]=useState(false),[night,setNight]=useState(false),[layers,setLayers]=useState(false),[help,setHelp]=useState(false),[selected,setSelected]=useState<Building|null>(null),[toast,setToast]=useState(''),[stats,setStats]=useState({population:0,trees:0,buildings:0}),[clock,setClock]=useState(8*60+30),[zoom,setZoom]=useState(100),[coords,setCoords]=useState({x:1200,y:850});
  const live=useRef({tool,paused,speed,labels,grid,night});live.current={tool,paused,speed,labels,grid,night};
  const toastTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
  const announce=useCallback((message:string)=>{setToast(message);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),3200);},[]);
  useEffect(()=>{
    const canvas=canvasRef.current!,mini=miniRef.current!,ctx=canvas.getContext('2d')!,mc=mini.getContext('2d')!;
    const world=createWorld();
    const cached=document.createElement('canvas');cached.width=W;cached.height=H;const bg=cached.getContext('2d')!;
    const buildings=document.createElement('canvas');buildings.width=W;buildings.height=H;const objects=buildings.getContext('2d')!;
    let width=1,height=1,baseZoom=1,raf=0,last=performance.now(),elapsed=0,time=8*60+30,uiTimer=0,drag:{x:number;y:number;cx:number;cy:number;distance:number;id:number}|null=null,hover:{x:number;y:number}|null=null;
    const camera:Camera={x:W/2,y:H/2,zoom:1};
    function updateStats(){setStats({population:world.buildings.filter(b=>b.kind==='home').reduce((n,b)=>n+b.people,0),trees:world.trees.length,buildings:world.buildings.length});}
    function refresh(){bg.clearRect(0,0,W,H);objects.clearRect(0,0,W,H);renderGround(bg,world);renderObjects(objects,world);updateStats();}
    const clamp=()=>{camera.zoom=Math.max(baseZoom*.72,Math.min(2.8,camera.zoom));camera.x=Math.max(0,Math.min(W,camera.x));camera.y=Math.max(0,Math.min(H,camera.y));setZoom(Math.round(camera.zoom/baseZoom*100));};
    const changeZoom=(factor:number)=>{camera.zoom*=factor;clamp();};
    function focus(b?:Building){if(b){camera.x=b.x+b.w/2;camera.y=b.y+b.h/2;camera.zoom=Math.max(baseZoom*2.3,.95);setSelected(b);}else{camera.x=W/2;camera.y=H/2;camera.zoom=baseZoom;}clamp();}
    function resize(){const box=canvas.getBoundingClientRect();width=box.width;height=box.height;const dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=width*dpr;canvas.height=height*dpr;const previous=baseZoom;baseZoom=Math.min(width/W,height/H)*1.08;camera.zoom*=baseZoom/previous;clamp();}
    const local=(e:{clientX:number;clientY:number})=>{const box=canvas.getBoundingClientRect();return{x:(e.clientX-box.left-width/2)/camera.zoom+camera.x,y:(e.clientY-box.top-height/2)/camera.zoom+camera.y};};
    const edit=(t:Tool,x:number,y:number)=>{const result=place(world,t,x,y);refresh();announce(result);return result;};
    engine.current={world,camera,refresh,focus,zoom:changeZoom,edit};
    const unregisterTools=registerCityTools(world,edit);
    const down=(e:PointerEvent)=>{if(e.button!==0&&e.button!==1)return;canvas.focus();canvas.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,cx:camera.x,cy:camera.y,distance:0,id:e.pointerId};};
    const move=(e:PointerEvent)=>{hover=local(e);setCoords({x:Math.round(hover.x),y:Math.round(hover.y)});if(drag&&drag.id===e.pointerId){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.distance=Math.max(drag.distance,Math.hypot(dx,dy));camera.x=drag.cx-dx/camera.zoom;camera.y=drag.cy-dy/camera.zoom;clamp();}};
    const up=(e:PointerEvent)=>{if(!drag||drag.id!==e.pointerId)return;const distance=drag.distance;drag=null;canvas.releasePointerCapture(e.pointerId);if(distance>5)return;const p=local(e);if(live.current.tool==='explore'){const b=[...world.buildings].reverse().find(b=>p.x>=b.x-7&&p.x<=b.x+b.w+7&&p.y>=b.y-b.height-30&&p.y<=b.y+b.h+8);if(b)setSelected(b);}else edit(live.current.tool,p.x,p.y);};
    const cancel=()=>{drag=null;};
    const wheel=(e:WheelEvent)=>{e.preventDefault();const p=local(e);changeZoom(e.deltaY>0?.9:1.1);const after=local(e);camera.x+=p.x-after.x;camera.y+=p.y-after.y;clamp();};
    const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('button,input,[role="dialog"]'))return;const d=70/camera.zoom;switch(e.key.toLowerCase()){case ' ':e.preventDefault();setPaused(v=>!v);break;case 'w':case 'arrowup':e.preventDefault();camera.y-=d;break;case 's':case 'arrowdown':e.preventDefault();camera.y+=d;break;case 'a':case 'arrowleft':e.preventDefault();camera.x-=d;break;case 'd':case 'arrowright':e.preventDefault();camera.x+=d;break;case '+':case '=':changeZoom(1.2);break;case '-':changeZoom(1/1.2);break;case '1':setTool('explore');break;case '2':setTool('tree');break;case '3':setTool('home');break;case '4':setTool('erase');break;case 'escape':setTool('explore');break;case '0':focus();break;}clamp();};
    const miniMove=(e:PointerEvent)=>{const r=mini.getBoundingClientRect();camera.x=(e.clientX-r.left)/r.width*W;camera.y=(e.clientY-r.top)/r.height*H;clamp();};
    canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',cancel);canvas.addEventListener('wheel',wheel,{passive:false});window.addEventListener('keydown',key);mini.addEventListener('pointerdown',miniMove);
    const observer=new ResizeObserver(resize);observer.observe(canvas);refresh();resize();
    function label(text:string,x:number,y:number,color='#f0e5c7') {ctx.font='600 13px "PingFang SC", "Microsoft YaHei", sans-serif';const screenX=(x-camera.x)*camera.zoom+width/2,screenY=(y-camera.y)*camera.zoom+height/2;const tw=ctx.measureText(text).width;if(screenX<0||screenX>width||screenY<0||screenY>height)return;ctx.fillStyle='#223c39db';ctx.fillRect(screenX-tw/2-10,screenY-11,tw+20,25);ctx.fillStyle=color;ctx.textAlign='center';ctx.fillText(text,screenX,screenY+6);}
    function frame(now:number){const dt=Math.min((now-last)/1000,.06);last=now;const opts=live.current;if(!opts.paused){const simDt=dt*opts.speed;elapsed+=simDt;time+=simDt*2;updateAgents(world,simDt);}const dpr=canvas.width/width;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#6f9560';ctx.fillRect(0,0,width,height);ctx.save();ctx.translate(Math.round(width/2-camera.x*camera.zoom),Math.round(height/2-camera.y*camera.zoom));ctx.scale(camera.zoom,camera.zoom);ctx.imageSmoothingEnabled=false;ctx.drawImage(cached,0,0);drawAgents(ctx,world,elapsed);ctx.drawImage(buildings,0,0);
      const hour=(time/60)%24;const dusk=opts.night?1:hour>=19||hour<5?1:hour>=17?(hour-17)/2:hour<7?(7-hour)/2:0;drawNight(ctx,world,dusk);
      if(opts.grid){ctx.strokeStyle='#edf4c330';ctx.lineWidth=1/camera.zoom;ctx.beginPath();for(let x=0;x<W;x+=32){ctx.moveTo(x,0);ctx.lineTo(x,H);}for(let y=0;y<H;y+=32){ctx.moveTo(0,y);ctx.lineTo(W,y);}ctx.stroke();}
      if(hover&&opts.tool!=='explore'){ctx.globalAlpha=.58;if(opts.tool==='home')drawBuilding(ctx,{id:'ghost',name:'',kind:'home',x:Math.round(hover.x/8)*8-36,y:Math.round(hover.y/8)*8-28,w:72,h:56,height:36,color:2,people:4});else if(opts.tool==='tree')drawTree(ctx,{x:hover.x,y:hover.y,variant:0});else{ctx.strokeStyle='#ed907a';ctx.lineWidth=3;ctx.strokeRect(hover.x-20,hover.y-20,40,40);}ctx.globalAlpha=1;}ctx.restore();
      if(opts.labels){world.buildings.filter(b=>b.kind!=='home'&&b.kind!=='shop').forEach(b=>label(b.name,b.x+b.w/2,b.y+b.h+33,['primary','middle','high','university'].includes(b.kind)?'#efd299':'#e1ead8'));label('梧 桐 里',408,620);label('东 岸 花 园',1960,620);label('青 禾 社 区',410,1408);label('青 河',riverX(750),752,'#a4dadd');}
      mc.imageSmoothingEnabled=false;mc.clearRect(0,0,mini.width,mini.height);mc.drawImage(cached,0,0,mini.width,mini.height);mc.drawImage(buildings,0,0,mini.width,mini.height);mc.fillStyle='#132b363d';mc.fillRect(0,0,mini.width,mini.height);mc.strokeStyle='#f5d58c';mc.lineWidth=2;const vw=width/camera.zoom/W*mini.width,vh=height/camera.zoom/H*mini.height;mc.strokeRect(camera.x/W*mini.width-vw/2,camera.y/H*mini.height-vh/2,vw,vh);mc.fillStyle='#f2d08b';mc.fillRect(camera.x/W*mini.width-2,camera.y/H*mini.height-2,4,4);
      uiTimer+=dt;if(uiTimer>.4){setClock(Math.floor(time));uiTimer=0;}raf=requestAnimationFrame(frame);
    }raf=requestAnimationFrame(frame);
    return()=>{unregisterTools();cancelAnimationFrame(raf);observer.disconnect();canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('pointercancel',cancel);canvas.removeEventListener('wheel',wheel);window.removeEventListener('keydown',key);mini.removeEventListener('pointerdown',miniMove);engine.current=null;clearTimeout(toastTimer.current);};
  },[announce]);
  const focusPlace=(name:string)=>{const b=engine.current?.world.buildings.find(b=>b.name===name);if(b)engine.current?.focus(b);};
  const h=Math.floor(clock/60)%24,m=clock%60,isDark=night||h>=19||h<6;
  return <TooltipProvider delay={200}><main className="city-app">
    <header className="topbar"><div className="brand"><div className="brand-icon"><Building2 size={25}/></div><div><h1>青河市<span>QINGHE</span></h1><p>像素世界 · 自由沙盒</p></div></div><div className="world-badge"><span className="status-dot"/>世界正在发生<span className="tiny-divider"/>种子 2417</div><div className="top-actions"><span className="weather">{isDark?<Moon size={18}/>:<Sun size={18}/>}<span>{isDark?'晴朗夜空':'晴 · 微风'}</span></span><button className="mode-button" onClick={()=>{setTool(tool==='explore'?'home':'explore');announce(tool==='explore'?'选择空地，放置你的第一栋住宅':'已切换到探索模式');}}><span className="mode-dot"/>{tool==='explore'?'自由探索':'建造模式'}<ChevronRight size={14}/></button></div></header>
    <section className="world-view" aria-label="青河市交互沙盒地图"><canvas ref={canvasRef} className={`world-canvas ${tool!=='explore'?'building-cursor':''}`} aria-label="像素城市地图。拖动平移，滚轮缩放。使用数字 1 到 4 选择工具，方向键移动。" tabIndex={0}/>
      <aside className="city-overview panel"><div className="eyebrow"><span className="status-dot"/>城市概况<span className="live-tag">LIVE</span></div><div className="overview-title">一座城市，<br/>无数个小日常。</div><div className="city-stats"><div><Users size={15}/><strong>{stats.population}</strong><span>居民</span></div><div><Building2 size={15}/><strong>{stats.buildings}</strong><span>建筑</span></div><div><TreePine size={15}/><strong>{stats.trees}</strong><span>树木</span></div></div><div className="overview-foot"><span className="soft-dot"/>{paused?'时间已暂停':h<7?'城市正在醒来':h<17?'街道上，人来人往':h<20?'晚风吹过河畔':'万家灯火，夜色温柔'}</div></aside>
      <nav className="side-tools panel" aria-label="地图工具"><IconButton label="城市全景 · 0" onClick={()=>engine.current?.focus()}><Compass size={20}/></IconButton><IconButton label="地图图层" active={layers} onClick={()=>setLayers(!layers)}><Layers3 size={20}/></IconButton><IconButton label="切换夜景" active={night} onClick={()=>setNight(!night)}>{night?<Moon size={20}/>:<Sun size={20}/>}</IconButton><div className="tool-divider"/><IconButton label="操作指南" active={help} onClick={()=>setHelp(!help)}><HelpCircle size={20}/></IconButton></nav>
      {layers&&<div className="layers-panel panel"><div className="small-panel-title">地图图层<button aria-label="关闭图层" onClick={()=>setLayers(false)}><X size={15}/></button></div><label>建筑名称<Switch checked={labels} onCheckedChange={setLabels} aria-label="建筑名称"/></label><label>建造网格<Switch checked={grid} onCheckedChange={setGrid} aria-label="建造网格"/></label><label>夜景模式<Switch checked={night} onCheckedChange={setNight} aria-label="夜景模式"/></label></div>}
      {help&&<div className="help-panel panel"><div className="small-panel-title">在青河漫游<button aria-label="关闭操作指南" onClick={()=>setHelp(false)}><X size={15}/></button></div><p>拖动地图平移，滚轮缩放。<br/>触屏可单指拖动，用 ＋ / − 缩放。<br/>点击建筑查看详情。<br/>点击缩略地图，快速抵达。</p><div className="key-row"><kbd>W A S D</kbd><span>移动视野</span></div><div className="key-row"><kbd>空格</kbd><span>暂停 / 继续</span></div><div className="key-row"><kbd>1 — 4</kbd><span>切换工具</span></div><div className="key-row"><kbd>0</kbd><span>城市全景</span></div></div>}
      <aside className="right-stack"><div className="minimap-panel panel"><div className="minimap-title"><span><Navigation size={15}/>城市缩略图</span><span className="north">N ↑</span></div><canvas ref={miniRef} width={264} height={187} className="minimap" aria-label="点击缩略地图定位" role="img"/><div className="minimap-foot"><span>青河 · 全域地图</span><span>点击定位</span></div></div><div className="places-panel panel"><div className="eyebrow">城市里的学校<span>04</span></div>{places.map((p,i)=><button className="place-item" key={p.name} onClick={()=>focusPlace(p.name)}><span className="place-icon" style={{color:p.color,background:p.color+'12'}}><p.icon size={19}/></span><span><strong>{p.name}</strong><small>{p.sub}</small></span><span className="place-level">{['小学','初中','高中','大学'][i]}</span><ChevronRight size={13}/></button>)}<div className="places-footer"><MapPin size={12}/>点击学校，前往校园</div></div></aside>
      <div className="compass-mark"><span>N</span><Navigation size={29}/><span>青河 / QINGHE</span></div>
      <div className="zoom-controls panel"><IconButton label="放大" onClick={()=>engine.current?.zoom(1.2)}><Plus size={19}/></IconButton><span>{zoom}%</span><IconButton label="缩小" onClick={()=>engine.current?.zoom(1/1.2)}><Minus size={19}/></IconButton><span className="zoom-divider"/><IconButton label="适应城市全景" onClick={()=>engine.current?.focus()}><Maximize size={16}/></IconButton></div>
      <div className="bottom-dock"><div className="tool-hint"><Move size={13}/>{tool==='explore'?'拖动探索 · 滚轮缩放 · 点击建筑':tool==='tree'?'点击空地种树 · 拖动移动视野':tool==='home'?'点击空地建造住宅 · 拖动移动视野':'点击移除你放置的房屋或树木'}</div><div className="build-tools panel">{([{id:'explore',name:'探索',icon:MousePointer2},{id:'tree',name:'种树',icon:TreePine},{id:'home',name:'住宅',icon:Home},{id:'erase',name:'移除',icon:Trash2}] as const).map((t,i)=><button key={t.id} aria-pressed={tool===t.id} className={`build-tool ${tool===t.id?'selected':''}`} onClick={()=>setTool(t.id)}><span className="tool-number">{i+1}</span><t.icon size={23}/><span>{t.name}</span></button>)}</div></div>
      <div className="time-panel panel"><div className="clock-icon">{isDark?<Moon size={21}/>:<Sun size={23}/>}</div><div className="time-readout"><strong>{String(h).padStart(2,'0')}<span>:</span>{String(m).padStart(2,'0')}</strong><small>第 {Math.floor(clock/1440)+1} 天 · {isDark?'夜晚':'白昼'}</small></div><div className="time-divider"/><IconButton label={paused?'继续模拟 · 空格':'暂停模拟 · 空格'} onClick={()=>setPaused(!paused)}>{paused?<Play size={17}/>:<Pause size={17}/>}</IconButton>{[1,2,5].map(s=><button key={s} onClick={()=>setSpeed(s)} aria-pressed={speed===s} className={`speed-button ${speed===s?'chosen':''}`}>{s}×</button>)}</div>
      {toast&&<div className="toast panel" role="status"><Check size={16}/>{toast}</div>}
    </section>
    <footer className="statusbar"><span><span className="status-dot"/>{paused?'模拟已暂停':'模拟运行中'}<span className="status-separator">/</span>自由沙盒</span><span className="coordinate">X {coords.x.toString().padStart(4,'0')}<span>Y {coords.y.toString().padStart(4,'0')}</span></span><span>每一个像素，都有生活。</span></footer>
    <Sheet open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><SheetContent className="building-sheet"><SheetHeader><div className="detail-icon">{selected&&['primary','middle','high','university'].includes(selected.kind)?<School size={34}/>:<Building2 size={34}/>}</div><div className="eyebrow">{selected&&TYPE_NAMES[selected.kind]}</div><SheetTitle className="detail-title">{selected?.name}</SheetTitle><SheetDescription className="detail-description">{selected&&descriptions[selected.kind]}</SheetDescription></SheetHeader><div className="detail-content"><div className="detail-fact"><Users size={18}/><span>{selected?.kind==='home'?'居住人数':['primary','middle','high','university'].includes(selected?.kind||'')?'规划学生容量':'空间容量'}</span><strong>{selected?.people} 人</strong></div><div className="detail-fact"><MapPin size={18}/><span>城市坐标</span><strong>{selected?.x}, {selected?.y}</strong></div><div className="detail-fact"><Clock3 size={18}/><span>当前世界时间</span><strong>{String(h).padStart(2,'0')}:{String(m).padStart(2,'0')}</strong></div><button className="detail-focus" onClick={()=>{if(selected)engine.current?.focus(selected);setSelected(null);}}>在地图上查看<Navigation size={16}/></button><p className="detail-note">城市中的居民与车辆沿街道实时移动。此处人数为场景设定，学校容量不计入常住人口。</p></div></SheetContent></Sheet>
  </main></TooltipProvider>;
}
